version: '3.9'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql_crud
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: crud_python
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my-app/BD/crud_python.sql:/docker-entrypoint-initdb.d/crud_python.sql

  flask_app:
    build:
      context: ./my-app
    container_name: flask_crud
    restart: always
    depends_on:
      - mysql
    ports:
      - "5600:5600"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: crud_python

volumes:
  mysql_data: